version: "3.9"
services:

  postgres:
    image: postgres:latest
    container_name: myblog_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "myblog"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"